services:
  mysql:
    container_name: mysql-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    ports:
      - "3307:3307"
    volumes:
      -  /Users/brittaalex/Documents/workstation/mtech-worskpace/nus/db/auth/mysql:/var/lib/mysql
    networks:
      - task-tracker-auth-network

networks:
  task-tracker-auth-network:
    external: true


