services:
  mysql:
    container_name: mysql
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    ports:
      - "3306:3306"
    volumes:
      - /Users/balajisivaprakasam/Desktop/SiBa/CODE_FILES/mysql:/var/lib/mysql
    networks:
      - task-tracker-auth-network

networks:
  task-tracker-auth-network:
    external: true


