apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: prd
  labels:
    app: auth-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-api
  template:
    metadata:
      labels:
        app: auth-api
    spec:
      containers:
        - name: auth-prd
          image: nusissgroup6/auth-prd:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8688
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: auth-configs
                  key: SPRING_PROFILES_ACTIVE

            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: auth-configs
                  key: SPRING_DATASOURCE_URL

            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DB_USERNAME

            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: DB_PASSWORD

            - name: TASK_TRACKER_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: auth-secrets
                  key: TASK_TRACKER_JWT_SECRET


---

apiVersion: v1
kind: Service
metadata:
  name: auth-deployment
  namespace: prd
  labels:
    app: auth-api
spec:
  selector:
    app: auth-api
  ports:
    - protocol: TCP
      port: 8688
      targetPort: 8688
  type: LoadBalancer